server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: local
  config:
    import: "configserver:"
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: catalog
              uri: lb://catalog-service
              predicates:
                - Path=/catalog/**
              filters:
                - StripPrefix=1

management:
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: env
