server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TheDarkHorse111/ecommerce-config.git
          default-label: master
          username: ${CONFIG_GIT_USERNAME:}
          password: ${CONFIG_GIT_TOKEN:}
        monitor:
          github:
            webhook-secret: ${GITHUB_WEBHOOK_SECRET:}
    stream:
      binders:
        bus:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092
      bindings:
        springCloudBusInput:
          binder: bus
        springCloudBusOutput:
          binder: bus

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
